README.md, doc/debian-based-installation.md, doc/rpm-based-installation.md, stream-loader.py
=> Issue 6.dockter.1

stream-loader.py
ISSUE-10
Gives user a way to determine how much time is spent pulling data off of Kafka.
=> issue-10 Added kafka-test subcommand

Dockerfile, README.md, requirements.txt
=> issue-1- Cleanup

Dockerfile
ISSUE-13
Allows different base images.
=> issue-13 Added ARG/FROM

Dockerfile, README.md
ISSUE-16
Need to be on Debian base.
=> Issue 16.dockter.1

Dockerfile, README.md
=> issue-16 moved to senzing/senzing-base

Dockerfile, README.md, requirements.txt, stream-loader.py
ISSUE-20
To enable pulling data from RabbitMQ as an alternative to Kafka
Enable pulling data from RabbitMQ.
=> Issue 20.jadair.1

README.md
=> issue-16 Add to configuration

stream-loader.py
ISSUE-29
DATA_SOURCE and ENTITY_TYPE parameters were not being set.
=> issue-29 Add setting of explicity DATA_SOURCE and ENTITY_TYPE

stream-loader.py
Much better performance with prefetch > 1. Specific value will depend on system, but we saw a significant increase in performance with 10.
=> Increasing prefetch count to 10

stream-loader.py
ISSUE-31
ConfigParser was trying to do variable replacement and was getting tripped up by a percent sign (%) in the CONFIGURATION password.
=> issue-31 Change from ConfigParser to RawConfigParser

stream-loader.py
=> issue-33 Database performance tests.

README.md
=> issue-35 Document formatting

CODE_OF_CONDUCT.md, Dockerfile, docker-compose.test.yml, rootfs/app/container-test.sh, rootfs/app/healthcheck.sh, stream-loader.py
=> issue-38 Passed inspectDockerImage

stream-loader.py
=> issue-38 Updated comment

stream-loader.py
=> issue-38 Print license periodically

stream-loader.py
=> Fixes for 1.9 changes.

CHANGELOG.md, Dockerfile, stream-loader.py
=> issue-46 Migrate to Python3

CHANGELOG.md, Dockerfile
=> issue-46 Specifiy version of senzing/senzing-base

stream-loader.py
=> Issue 46.dockter.3

stream-loader.py
=> Issue 50.dockter.1

CHANGELOG.md, Dockerfile, README.md, rootfs/app/container-test.sh
=> issue-52 Update to senzing/senzing-base:1.1.0

CHANGELOG.md, stream-loader.py
=> issue-52 Add the ability to delay processing

CHANGELOG.md, Dockerfile, Makefile, README.md, stream-loader.py
=>  issue-55 Update for RPM installation 

Dockerfile
=> issue-55 Adjust FROM

CHANGELOG.md
=> issue-55 Update release date

stream-loader.py
=> issue-60 Remove TranslateG2ModuleException

README.md, docs/debian-based-installation.md, stream-loader.py
=> issue-62 Improved error recovery 

stream-loader.py
=> issue-64 Improved license expiry messages

CHANGELOG.md
=> issue-64 Prepare for version

.dockerignore, PULL_REQUEST_TEMPLATE.md, README.md
=> issue-67 Refactor to template

Dockerfile, Makefile, README.md
=> #71 Refactor to template

CHANGELOG.md, stream-loader.py
=> issue-70 Support for `SENZING_ENGINE_CONFIGURATION_JSON`

stream-loader.py
=> issue-74 Create a "governor" to control the speed or pause ingestion.

stream-loader.py
None
Issue number: #76 
Prefetch was hard coded and to low
Allows users to set prefetch and uses a default that gives better and smoother performance
=> Issue 76.jadair.1

CHANGELOG.md
Updating changelog for 1.3.2 release
=> Updating changelog for 1.3.2

stream-loader.py
=> #74 make Governor more specific

CHANGELOG.md, Dockerfile, stream-loader.py
=> #74 Prepare for release

CHANGELOG.md, Dockerfile
=> #81 Update to senzing/senzing-base:1.4.0

CHANGELOG.md, README.md, stream-loader.py
=> issue-83 Add info and error queues

CHANGELOG.md, stream-loader.py
=> issue-83 Post code review changes

stream-loader.py
=> #83 Add commandline options

.github/workflows/cd-3hr-cron-test-debian-build.yml, .github/workflows/cd-pr-test-debian-build.yml, Makefile, test.txt
Issue number: #90
steps towards building a cd pipeline
add build pipeline
=> Issue 90.mahchiahui.1

README.md, stream-loader.py
=> issue-83 Simplify cli option

Makefile
=> #83 Cleanup whitespace. space > tabs

CHANGELOG.md
=> #83 Prepare for version

stream-loader.py
=> issue-83 Improve logging

stream-loader.py
=> #83 Fix CLI parameters

Dockerfile, Makefile
=> #108 update to senzing/senzing-base:1.5.0

CHANGELOG.md, Dockerfile, stream-loader.py
=> Issue 82.dockter.1

README.md
=> #112 migrate to stream-producer

README.md
=> #115 Update information for AWS SQS

requirements.txt
=> #121 Added boto3

.github/workflows/cd-pr-test-debian-build.yml, Dockerfile, Makefile
=> Issue 119.macy.1

CHANGELOG.md, stream-loader.py
=> Issue 127.dockter.1

stream-loader.py
=> #117 Optional exit when queue is empty SENZING_EXIT_ON_EMPTY_QUEUE

stream-loader.py
=> Issue 117.dockter.2

stream-loader.py
=> #131 Added new messages

stream-loader.py
=> #117 Add SENZING_EXIT_SLEEP_TIME_IN_SECONDS

stream-loader.py
=> #117 Support AWS SQS Dead-letter queue

stream-loader.py
=> #117 Fix incorrect variable

stream-loader.py
Issue number: #87 
Enable connecting to customer configured and tuned queue
=> Adding option to passively attach to an queue and making that the default behavior

stream-loader.py
=> #117 Add missing class variable

Dockerfile, stream-loader.py
=> Issue 145.dockter.1

CHANGELOG.md
=> #145 Prepare for release

README.md, docs/README.md, docs/index.css, docs/index.html
=> Issue 149.dockter.1

docs/index.html
=> #149 Ready for publish

docs/index.html
=> #149 Add ansible

docs/index.html
=> #149 Add support

docs/index.html
=> #149 Move to /certification/data

CHANGELOG.md, stream-loader.py
=> Issue 157.dockter.1

docs/index.html
=> #149 Add Updated

stream-loader.py
Issue number: #160 
Rabbitmq connections were timing out after 60 seconds. That is not very long. Now the timeout is settable.
Allow configuring the rabbitmq heartbeat.
=> Exposing heartbeat as a settable parameter

stream-loader.py
=> #164 Debugging: Add parameter for G2Engine

stream-loader.py
Issue number: #171
The file url feature doesn't work and gave error on non-existing variable.
Fixes the file url problem.
=> #171 fix file url.

CHANGELOG.md, stream-loader.py
=> Issue 174.dockter.1

CHANGELOG.md, stream-loader.py
=> Issue 174.dockter.2

stream-loader.py
Issue number: #179 
Log output was wrongly logging the exchange name as the queue, and not logging the queue name or the routing key.
- Logging the exchange, queue, and routing key when an error is encountered. 
- Fixing some errors flagged by pylint.
=> Issue 179.jadair.1

CHANGELOG.md, stream-loader.py
=> Issue 182.dockter.1

docs/index.html
=> #174 Change certified.senzing.com to hub.senzing.com

stream-loader.py
Issue number: #84 
We need faster way to get records to stream-loader. stream-producer can now load multiple records into a message in a json array
Handle json array with multiple records, as well as still supporting other existing single record messages.
=> Microbatching

CHANGELOG.md, Dockerfile, stream-loader.py
=> #195 Massaged code

stream-loader.py
=> #195 Fix URL

stream-loader.py
Issue number: #202 
To make the info queue delay time on SQS configurable
Configuration flexibility
=> Make delay time on info queue configurable

CHANGELOG.md, Dockerfile, README.md, stream-loader.py
=> #202  Prepare for versioned release

README.md
=> remove reference to SENZING_PROCESSES

CHANGELOG.md, stream-loader.py
=> Issue 207.dockter.2

README.md
=> #212 Update to senzingdata 2.0.0

stream-loader.py
=> Redact engine_configuration_json

docs/errors.md
=> #1 Added senzing-50010567

CHANGELOG.md, stream-loader.py
Issue number: #201 
RabbitMQ Virtual Host is now a settable parameter
=> Issue 201.jadair.1

stream-loader.py
Issue number: #196 
Clean up exception handling, pylint fixes,
=> Issue 196.jadair.1

CHANGELOG.md, README.md, stream-loader.py
=> Issue 220.dockter.1

.dockerignore, CHANGELOG.md, Dockerfile
=> update senzing base version

CHANGELOG.md, Dockerfile
=> #224 update to senzing base 1.6.1

stream-loader.py
=> #227 added performance timing

CHANGELOG.md, Dockerfile
=> #227 added performance timing change log for new release

stream-loader.py
Issue number: #187 
To catch errors from checking the default config ID
=> Catching exceptions from checking default config ID

.gitignore, CHANGELOG.md, Dockerfile, Dockerfile-with-data, Makefile, stream-loader.py
=> Issue 231.dockter.1

CHANGELOG.md, Dockerfile, requirements.txt, stream-loader.py
=> Issue 235.dockter.1

stream-loader.py
=> #239 updated usage info

Dockerfile-with-data
=> #250 removed erroneous * in copy command

Dockerfile, Dockerfile-with-data
Update underlying docker images.
Issue number: #1
=> github-util: Update FROM version

CHANGELOG.md
=> Prep for 1.9.3 release

CHANGELOG.md, Dockerfile, Dockerfile-with-data
=> Issue 259.ron.0

CHANGELOG.md, Dockerfile, stream-loader.py
=> Issue 260.dockter.1

CHANGELOG.md, Dockerfile, Dockerfile-with-data, stream-loader.py
=> Issue 246.dockter.1

CHANGELOG.md, Dockerfile, Dockerfile-with-data, stream-loader.py
=> Issue 260.dockter.2

CHANGELOG.md, Dockerfile, Dockerfile-with-data, stream-loader.py
=> Issue 246.dockter.2

CHANGELOG.md, Dockerfile, Dockerfile-with-data, stream-loader.py
=> Issue 270.dockter.1

CHANGELOG.md, stream-loader.py
=> #227 Remove V2

CHANGELOG.md, Dockerfile, Dockerfile-with-data, Makefile, stream-loader.py
=> #280 Update to senzingdata-v3

hooks/build
=> #284 Delete docker hooks directory

hooks/build
=> #284 Add build hook

hooks/build
=> #284 Fixed logic

hooks/build
=> #284 Improved build script

hooks/build
=> #284 Sync to template

CHANGELOG.md, Dockerfile, Dockerfile-with-data, stream-loader.py
=> #298 Added libodbc1

.github/workflows/cd-pr-test-debian-build.yml, CONTRIBUTING.md, README.md, docs/debian-based-installation.md, docs/errors.md, docs/index.html, docs/rpm-based-installation.md, stream-loader.py
=> #283 Migrate from master to main

CHANGELOG.md, README.md, stream-loader.py
=> Issue 311.dockter.1

CHANGELOG.md, Dockerfile, Dockerfile-with-data, docs/debian-based-installation.md, docs/rpm-based-installation.md, stream-loader.py
=> Issue 312.dockter.1

CHANGELOG.md, Dockerfile, stream-loader.py
=> #312 Update dates

.github/CODEOWNERS, .github/workflows/add-dependabot-request-to-project-t-comm.yaml, .github/workflows/add-issue-to-project-t-comm.yaml, .github/workflows/add-triage-label.yaml, .github/workflows/build-docker-container.yaml, .github/workflows/identify-customer.yaml, .github/workflows/pylint.yaml
=> #338 rename pull-request-tests.yaml

CHANGELOG.md, Dockerfile, README.md, stream-loader.py
=> #347 Update to SENZING_AZURE_QUEUE_CONNECTION_STRING

CHANGELOG.md, stream-loader.py
=> #314 Remove support for ENTITY_TYPE

stream-loader.py
=> Remove exit on expired license

README.md
=> #371 Add License

CHANGELOG.md, Dockerfile, stream-loader.py
=> #401 Prepare for versioning

.pylintrc, CHANGELOG.md, Dockerfile, requirements.txt, stream-loader.py
=> Issue 414.dockter.1

CHANGELOG.md, Dockerfile, stream-loader.py
=> #414 Prepare for versioned release

CHANGELOG.md, stream-loader.py
=> Issue 464.ron.0

.github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml
Issue number: senzing-factory/build-resources#69
=> senzing-factory/build-resources#69 add missed updates

CHANGELOG.md, Dockerfile
=> #844 Prepare for versioned release

CHANGELOG.md, Dockerfile
=> #1219 Update senzing_governor.py URL

README.md
=> #1226 Deprecate
